- name: Apply Terraform via Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - cloud.terraform

  tasks:
    - name: Run terraform init (explicit)
      command: terraform init
      args:
        chdir: ../terraform_project
        
    - name: Run terraform apply
      cloud.terraform.terraform:
        project_path: ../terraform_project
        state: present

    - name: Get terraform output
      cloud.terraform.terraform_output:
        project_path: ../terraform_project
      register: tf_output

    - name: Show instance IDs
      debug:
        msg: "Created instance IDs: {{ tf_output.outputs.instance_ids.value }}"
